substitutions:
# Change the disp_name to something you want  
  dnum: "1"
  dname: arlec_pb89ha
  sname: pb89
  location: spare
  full_name: ${location}_${dname}_${dnum}
  short_name: ${location}_${sname}_${dnum}

esphome:
  name: ${full_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${full_name} Hotspot"
    password: "r1HmbMpHTwNe"

captive_portal:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80

# Enable logging
logger:
  #level: VERBOSE


binary_sensor:
  - platform: gpio
    name: ${short_name}
    pin:
      number: GPIO3
      inverted: True
    id: button1
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at least 0.5s
      then:
        lambda: |-
          if (! id(relay1).state  ) {
            id(relay1).turn_on();
          } else if ( ! id(relay2).state ) {
            id(relay2).turn_on();
          } else if ( ! id(relay3).state ) {
            id(relay3).turn_on();
          } else if ( ! id(relay4).state ) {
            id(relay4).turn_on();
          } else {
            id(relay1).turn_off();
            id(relay2).turn_off();
            id(relay3).turn_off();
            id(relay4).turn_off();
          }
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 0.2s
      then:
        lambda: |-
          if ( id(relay1).state  ) {
            id(relay1).turn_off();
          } else if (  id(relay2).state ) {
            id(relay2).turn_off();
          } else if (  id(relay3).state ) {
            id(relay3).turn_off();
          } else if (  id(relay4).state ) {
            id(relay4).turn_off();
          } else {
            id(relay1).turn_on();
            id(relay2).turn_on();
            id(relay3).turn_on();
            id(relay4).turn_on();
          }
    - timing:
        - ON for at least 0.5s
        - OFF for at least 0.2s
      then:
        lambda: |-
          if (id(relay1).state || 
          id(relay2).state || 
          id(relay3).state || 
          id(relay4).state ) {
            id(relay1).turn_off();
            id(relay2).turn_off();
            id(relay3).turn_off();
            id(relay4).turn_off();
          } else {
            id(relay1).turn_on();
            id(relay2).turn_on();
            id(relay3).turn_on();
            id(relay4).turn_on();
          }

switch:
  - platform: gpio
    name: ${short_name}.1
    pin: GPIO5
    id: relay1
  - platform: gpio
    name: ${short_name}.2
    pin: GPIO4
    id: relay2
  - platform: gpio
    name: ${short_name}.3
    pin: GPIO13
    id: relay3
  - platform: gpio
    name: ${short_name}.4
    pin: GPIO12
    id: relay4

status_led:
  pin:
    number: GPIO1
    inverted: yes
