substitutions:
# Change the disp_name to something you want  
  dnum: "1"
  dname: deta_2g_switch
  sname: d2gs
  location: spare
  full_name: ${location}_${dname}_${dnum}
  short_name: ${location}_${sname}_${dnum}

esphome:
  name: ${full_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${full_name} Hotspot"
    password: "r1HmbMpHTwNe"

captive_portal:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG


binary_sensor:
  - platform: gpio
    name: ${short_name}.1
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True
    id: button1
    on_press:
      - switch.toggle: relay1

  - platform: gpio
    name: ${short_name}.2
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    id: button2
#    on_press:
#      - homeassistant.service:
#          service: script.bedside_toggle
#      - logger.log: "Button 2 pressed"
#      - switch.toggle: relay2
    on_click:
    - min_length: 50ms
      max_length: 350ms
      then:
        - homeassistant.service:
            service: script.bedside_toggle
        - logger.log: "Button 2 short pressed"
    - min_length: 500ms
      max_length: 1000ms
      then:
        - homeassistant.service:
            service: script.bedroom_toggle
        - logger.log: "Button 2 long pressed"

switch:
  - platform: gpio
    name: ${short_name}.1
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: ${short_name}.2
    pin: GPIO14
    id: relay2

status_led:
  pin:
    number: GPIO4
    inverted: yes
