esphome:
  name: red_salt
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:
  password: !secret api_pass

logger:

ota:
  password: !secret api_pass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Red Salt"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
web_server:
  port: 80