esphome:
  name: rf_bridge
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: 192.168.107.65
    gateway: 192.168.107.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
  
#sensor:
#  - platform: wifi_signal
#    name: Sonoff RF Bridge Wifi Signal
#    update_interval: 10s
#  - platform: uptime
#    name: Sonoff RF Bridge Uptime

binary_sensor:
  - platform: status
    name: Sonoff RF Bridge Status

remote_receiver:
  pin: 4
  dump: rc_switch
  tolerance: 50
  filter: 4us
  idle: 4ms

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: template
    name: Led Toggle On Off
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0101101101'
          protocol: 2
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010110110111000100000001'
          protocol: 1
