esphome:
  name: tv_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: 192.168.107.9
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.107.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret api_pass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "TV Lamp Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      #inverted: True
    name: "Foot Switch"
    id: foot_sw
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "TV Lamp Relay"
    pin: GPIO12
    id: relay

#status_led:
#  pin:
#    number: GPIO13
#    inverted: yes
    
web_server:
  port: 80
